listen_addresses = '*'
port = 5432
max_connections = 60
ssl = on
ssl_cert_file = '/run/tls/tls.crt'
ssl_key_file = '/run/tls/tls.key'
ssl_ca_file = '/run/tls/gateway-ca.crt'
ssl_min_protocol_version = 'TLSv1.2'
hba_file = '/etc/postgresql/pg_hba.conf'
ident_file = '/etc/postgresql/pg_ident.conf'
log_connections = on
log_disconnections = on
log_line_prefix = '%m [%p] user=%u db=%d app=%a '
log_statement = 'none'
